    spring.application.name=MockProject
    spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=quanlychungcu_project;encrypt=false;
    spring.datasource.username=sa
    spring.datasource.password=Anhnga2003@
spring.jpa.hibernate.ddl-auto=none
  spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
    spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
