services:

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SQL_SERVER_DB_SERVER_ADDRESS=db"
      - "SQL_SERVER_DB_SERVER_PORT=1433"
      - "SQL_SERVER_USER=sa"
      - "SQL_SERVER_PASSWORD=YourStrong@Passw0rd"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    depends_on:
      db:
        condition: service_healthy